/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 */

// sidebars.js

module.exports = {
  archiveSidebar: [
    {
      type: 'category',
      label: 'ZU × ORI Archive',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Story',
          items: [
            {
              type: 'autogenerated',
              dirName: 'story',
            },
          ],
        },
        {
          type: 'category',
          label: 'Characters',
          items: [
            {
              type: 'autogenerated',
              dirName: 'characters',
            },
          ],
        },
        {
          type: 'category',
          label: 'Research',
          items: [
            {
              type: 'autogenerated',
              dirName: 'research',
            },
          ],
        },
      ],
    },
  ],
};